# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install xcpretty
- gem install xcpretty-travis-formatter
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- xcrun simctl list

before_script:
- set -o pipefail
- xcodebuild test -enableCodeCoverage YES -workspace Example/STXLFUCache.xcworkspace -scheme STXLFUCache-Example -sdk iphonesimulator12.2 -destination 'platform=iOS Simulator,OS=12.2,name=iPhone XS' ONLY_ACTIVE_ARCH=NO | xcpretty

script:
- pod lib lint

branches:
  only:
    - master